#!/usr/bin/env python3

from random import randint as loteriada

FRAZY_PART_ONE = [
    "Nie jestem rasistą‚ ale", "Nie jestem homofobem‚ ale",
    "To chyba oczywiste‚ że", "W każdym normalnym kraju wiadomo‚ że",
    "Bądźmy szczerzy:", "Nie okłamujmy się:",
    "Nie boję się niewygodnej prawdy:",
    "Nie dajmy się zwariować politycznej poprawności:",
    "W USA już dawno dowiedziono‚ że", "To chyba logiczne:",
    "Na zdrowy rozum oczywiste jest‚ że", "Sam nie doznałem łaski wiary‚ ale",
    "Nie jestem seksistą‚ ale", "Jak słusznie zauważył Janusz Korwin-Mikke‚",
    "Jak słusznie mawia Jarosław Kaczyński‚", "Ja do Żydów nic nie mam‚ ale",
    "Ja sam uwielbiam kobiety‚ ale", "Jak mówi Mariusz Max Kolonko‚",
    "Pewnie i tak usuną ten komentarz‚ ale",
    "Pewnie i tak poddadzą mój komentarz stalinowskiej cenzurze‚ ale",
    "Znam wielu gejów‚ są miłymi ludźmi‚ ale",
    "Osobiście nie mam wątpliwości‚ że", "A ja się pokuszę o stwierdzenie‚ że",
    "Jak wspomniał Tomasz Terlikowski‚", "Nie od dziś wiadomo‚ że",
    "Wojciech Cejrowski już 20 lat temu powiedział‚ że",
    "Jak mawiał śp. Józef Glemp", "Jak ogłosił ostatnio Episkopat",
    "Jak mawia Ojciec Rydzyk",
    "Jak ewidentnie wynika z encyklik Jana Pawła II",
    "Jak celnie zauważył Rafał Ziemkiewicz", "Jak powszechnie wiadomo",
    "Jak wie każdy prawdziwy Polak", "Chyba nie ulega wątpliwości że",
    "Jak pisze w liście do wiernych przewodniczący Episkopatu Polski i metropolita poznański abp Stanisław Gądecki",
    "Jak twierdzą księża", "Powiedzmy wreszcie wprost",
    "Nie bójmy się powiedzieć że", "Jak napisano na portalu Fronda",
    "Zgodnie z artykułem z najnowszego numeru W Polityce",
    "Biskupi ostrzegają że", "Stolica Apostolska od dawna głosi że",
    "Nie żebym miał coś do homosiów ale", "Nie jestem antysemitą ale",
    "To powszechna wiedza że", "Chyba nikt normalny nie zaprzeczy że",
    "To oczywiste że", "Na antenie Telewizji Republika powiedziano że",
    "Bądźmy poważni:", "Choć nie jestem rasistą‚ przyznać trzeba‚ że",
    "Mimo że nie jestem homofobem‚ nie sposób nie zauważyć‚ że",
    "Oczywistym jest‚ że", "Nie należy się okłamywać:",
    "Nie lękajmy się niewygodnej prawdy:",
    "Pozwolę sobie na polityczną niepoprawność:",
    "Amerykańscy naukowcy dowiedli ostatnio‚ że",
    "Niepokorni dziennikarze odważyli się wspomnieć‚ że",
    "Nie jestem szowinistą ale", "Zgodnie z programem Kongresu Nowej Prawicy‚",
    "Jak mawiał ś.p. Lech Kaczyński‚", "Jak słusznie twierdzi Dominik Zdort‚",
    "Zgodnie z programem partii KORWiN", "Jak twierdzą eksperci Episkopatu",
    "Nikt tego nie ujął zgrabniej niż Andrzej Duda:",
    "Łukasz Warzecha jak zwykle celnie:", "Piotr Semka utrafił w sedno:",
    "Trzeba było słuchać Matki-Kurki:", "Wróble na dachu od dawna ćwierkają:",
    "Ekspertyzy Instytutu Ordo Iuris jasno dowodzą że", "Krótko mówiąc",
    "Chyba tylko ktoś po lewackim praniu mózgu zaprzeczy że",
    "Prawda jest taka że",
    "Trzeba być ogłupionym przez lewacką propagandę by nie widzieć że",
    "Jak podają media naprawdę niezależne",
    "Prof. Nowak w swoim wykładzie przypomniał że",
    "Już wielokrotnie pisałem że", "Gołym okiem widać że",
    "Ryszard Petru ma oczywistą rację:",
    "Profesor Balcerowicz niejednokrotnie wspominał że",
    "Jeremi Mordasewicz ocenia:"
]

FRAZY_PART_DWA = [
    "wysokie podatki tłamszą przedsiębiorczość‚",
    "Murzyni są mniej inteligentni‚", "geje deprawują młodzież‚",
    "Cyganie nic tylko kradną‚",
    "kościół jest potrzebny dla utrzymania moralności‚",
    "prawda leży pośrodku‚", "kobiety są głupsze od mężczyzn‚",
    "miejsce kobiet jest w kuchni‚", "mamy już pełne równouprawnienie‚",
    "kobiety dość już wywalczyły‚", "biali ludzie są prześladowani‚",
    "Kościół Katolicki jest ważny w polskim życiu społecznym‚",
    "Papież jest ważny dla wszystkich Polaków‚",
    "miejsce Murzynów jest w Afryce‚",
    "muzułmanie zagrażają bezpieczeństwu Europy‚",
    "molestowanie nie jest problemem‚", "Ukrainą rządzą banderowcy‚",
    "Unia Europejska to czwarty rozbiór Polski‚",
    "kobiety nie nadają się na wysokie stanowiska‚",
    "geje zbytnio się obnoszą‚", "Żydzi rządzą światem‚",
    "d***kracja jest idiotycznym systemem‚",
    "Szwecja jest na krawędzi bankructwa‚",
    "Unia Europejska chyli się ku upadkowi‚",
    "nie ma czegoś takiego jak biseksualizm‚",
    "homoseksualistów trzeba leczyć‚", "religia w szkole jest potrzebna‚",
    "należy chronić dzieci nienarodzone‚",
    "feministki tworzą kolejne problemy nie znane wcześniej normalnym ludziom‚",
    "ZSRE jest gorszy niż komuna‚",
    "nie chodzi o to by było po równo tylko sprawiedliwie‚",
    "własność prywatna jest święta‚", "reprywatyzacja po prostu się należy‚",
    "katolicyzm jest najbardziej prześladowaną religią‚",
    "chrześcijanie są w Polsce prześladowani‚",
    "przypadki pedofilii w Kościele są odosobnione i piętnowane‚",
    "feminizm kończy się gdy trzeba wnieść lodówkę na 8 piętro",
    "grozi nam upadek cywilizacji białego człowieka‚",
    "zachodnia cywilizacja bez chrześcijaństwa po prostu upadnie‚",
    "prawdziwa polska inteligencja zginęła w Katyniu‚",
    "musi być w tym jakieś ziarno prawdy",
    "przecież kobieta potrzebuje mężczyzny‚",
    "homoseksualizm jest dyspozycją negatywną‚",
    "nie da się karmić dzieci prezerwatywami‚",
    "idea walki z globalnym ociepleniem to wierutna bzdura",
    "pedały nie powinny wychodzić ze swoją seksualnością na ulicę‚",
    "lewica dławi się własnym jadem‚", "podatki to złodziejstwo‚",
    "ZUS okrada Polaków‚", "wszyscy powinniśmy być samozatrudnieni‚",
    "tzw. orientacja seksualna to wymysł zboczeńców‚",
    "kobiety lubią być molestowane‚",
    "najbardziej uprzywilejowaną grupą w Polsce są górnicy‚",
    "nauczyciele mają zbyt wiele przywilejów",
    "kodeks pracy należy zlikwidować",
    "tylko przedsiębiorcy powinni mieć prawo głosu‚",
    "in vitro wyrządza wiele zła‚", "to był zamach‚",
    "sprawa Smoleńska do dziś nie została należycie wyjaśniona‚",
    "jeśli słoikom nie podoba się w warszawie‚ mogą wyjechać‚ zamiast narzekać‚",
    "opluwanie wartości chrześcijańskich to znieważanie Polskości‚",
    "przedsiębiorcy to najbadziej dyskryminowana w Polsce grupa‚",
    "Ślązacy to zakamuflowana opcja niemiecka‚",
    "sojusz z USA wymaga poświęceń‚ nawet jeśli chodzi o zawieszenie praw człowieka terrorystów",
    "tak jak kiedyś rozkazy płynęły z Moskwy‚ tak teraz z Brukseli i nic się nie zmieniło",
    "wolny rynek jest koniecznością",
    "liberalna ekonomia to nie ideologia tylko nauka",
    "wychowanie bezstresowe prowadzi do zepsucia młodzieży",
    "pseudoekolodzy pewnie nam zaraz zakażą oddychać w ramach walki z globalnym ocipieniem",
    "aborcja to morderstwo",
    "Chrystus powinien zostać intronizowany na króla Polski",
    "ateiści są pozbawieni moralności", "Tusk to gorszy komunista od Stalina",
    "nawet normalni ateiści powinni szanować Papieża-Polaka",
    "Jan Tomasz Gross kłamie twierdząc‚ że Polacy zabijali Żydów‚",
    "geje są ohydni ale na lesbijki to można sobie popatrzeć",
    "w żadnej innej grupie nie ma tylu pedofili co wśród homosiów",
    "jedynym słusznym ustrojem jest monarchia absolutna",
    "tzw. partia Zielonych to tak naprawdę przefarbowani Czerwoni",
    "Polska jest Mesjaszem Narodów",
    "Kościół Katolicki nas wszystkich ubogaca",
    "nasze ustawodawstwo przeciwne życiu i obyczajom należy do grzechów społecznych",
    "w nieregularnych sytuacjach rodzinnych uszczerbku doznaje niestety wychowanie dzieci do wiary",
    "jesteśmy na krawędzi III wojny światowej",
    "nawet homoseksualiści mają szansę na nawrócenie",
    "potrzeba nam mężów stanu a nie politycznych gierek",
    "męki piekielne czekające grzeszników będą straszne",
    "Niemcy to odwieczni wrogowie polskości",
    "Rosjanie to odwieczni wrogowie polskości",
    "tzw. związki partnerskie to zagrożenie dla wielotysiącletniej historii instytucji małżeństwa",
    "Polska potrzebuje silnej armii",
    "ideologia gender jest jak broń nuklearna",
    "transseksualizm jest sprzeczny z prawami natury",
    "pragnienia Stwórcy są zapisane w naturze",
    "propagowanie teorii gender to ideologiczna kolonizacja",
    "uczciwy człowiek nie ma nic do ukrycia",
    "tylko katolicyzm może nas uratować przed islamem",
    "bez Kościoła nie ma Polski", "każdy uczciwy człowiek musi w coś wierzyć",
    "ateizm nie jest czymś normalnym", "homoseksualizm to choroba psychiczna",
    "należy zakazać promowania homoseksualizmu", "SLD należy zdelegalizować",
    "potrzebna jest dalsza lustracja", "potrzebujemy IV Rzeczypospolitej",
    "pigułka EllaOne to trutka na dzieci i na matki",
    "ten rząd zajmuje się zaspokajaniem lewackiej agendy",
    "istnienie i sprzedaż środków antykoncepcyjnych jest przeciwna interesowi narodowemu",
    "w myśl lewackiej cywilizacji śmierci zwierzęta są lepiej traktowane niż ludzie",
    "zwierzęta nie powinny mieć praw", "Tusk jest pachołkiem Putina",
    "Tusk walczy o interesy eurokratów a nie Polski", "Tusk to zdrajca Polski",
    "Wałęsa był agentem", "Oleksy był agentem",
    "większość POlityków to agenci", "Ruch Narodowy to prawdziwi patrioci",
    "najbardziej prześladowani są dziś biali heteroseksualni mężczyźni",
    "obecnie to mężczyźni są dyskryminowani",
    "absurdem jest żądanie aby kobiety zarabiały tyle co mężczyźni",
    "wszyscy Żołnierze Wyklęci to bohaterowie",
    "polskie podatki są za wysokie", "lewica ma jakąś obsesję na temat seksu",
    "lewica deprawuje polską młodzież", "wychowanie seksualne uczy perwersji",
    "polskich Tatarów należy deportować",
    "Lalka to powieść skrajnie antypolska",
    "trudno sobie wyobrazić inne rozwiązanie problemu zagrożenia islamskiego dla Europy niż deportację muzułmanów",
    "Państwo Islamskie jest jak bolszewicy",
    "Franciszek swym skrajnym liberalizmem zburzy Kościół i zbuduje nowe wyznanie",
    "homomałżeństwa naprawdę oznaczają więcej islamu w Europie",
    "kobieta która nie wyda na świat potomstwa jest po prostu nieszczęśliwa",
    "musi nastąpić dekolonizacja Polski",
    "Grecy są leniwi i sami sobie zasłużyli na swoją sytuację",
    "ustawa o in-vitro to mrożenie mordowanie i homoadopcja",
    "jedno dziecko to za mało by kobieta była szczęśliwa",
    "gender to prosty sposób na produkcję dewiantów",
    "Prawdy można dowiedzieć się głównie z Internetu",
    "Unia Europejska to nic innego niż polukrowana wersja Korei Północnej",
    "środowiska LGBT mogą obejść naturalne metody zapłodnienia i wejść tylnymi drzwiami",
    "nieomylność papieska nie dotyczy przyczyn globalnego ocieplenia",
    "antykoncepcja jest wbrew polskiej racji stanu",
    "gwałt może przynieść cud poczęcia",
    "UE przypomina Rzym tuż przed upadkiem",
    "Razem to szalupa ratunkowa dla SLDowców",
    "należy przyjąć jedynie chrześcijańskich uchodźców",
    "tzw. uchodźcy to nieroby które chcą żerować na naszym socjalu",
    "muzułmańscy uchodźcy to potencjalni terroryści",
    "dron aborcyjny to zmechanizowane mordowanie polskich obywateli",
    "Grecja potrzebuje dalszych cięć budżetowych",
    "tylko intronizacja Jezusa na króla Polski może rozwiązać problemy tego kraju",
    "skrajna lewica jak Syriza Podemos czy Razem jest dla Europy takim samym zagrożeniem jak ISIS"
]

FRAZY_PART_3 = [
    "wbrew temu‚ co twierdzi Krytyka Polityczna.",
    "wbrew temu‚ co twierdzi lewica.", "wbrew temu‚ co twierdzą komuniści.",
    "wbrew temu‚ co twierdzi lobby homoseksualne.",
    "wbrew temu‚ co uważa lewactwo.",
    "wbrew temu‚ co twierdzi homoseksualna propaganda.",
    "wbrew twierdzeniom ideologii gender.", "wbrew postulatom feministek.",
    "wbrew twierdzeniom osób o PRLowskiej mentalności.",
    "wbrew temu‚ co twierdzą lewacy.",
    "mimo lewackich artykułów na łamach Wyborczej.",
    "wbrew temu‚ co twierdzą różni Homo Sovieticus.",
    "wbrew tezom które lansują wiadome koła.",
    "wbrew temu‚ co twierdzi Salon.",
    "wbrew propagandzie mainstreamowych mediów.",
    "wbrew temu co mówią redaktorzy Wybiórczej.",
    "wbrew temu co twierdzi Szechter.",
    "mimo żałosnych prowokacji Jasia Kapeli.",
    "mimo goebbelsowskiej propagandy michnikowszczyzny.",
    "wbrew temu co twierdzą POpaprańcy.",
    "wbrew temu‚ co mówią ludzie o komunistycznej przeszłości.",
    "wbrew temu‚ co twierdzą byli agenci.", "wbrew kłamstwom lewaków.",
    "wbrew rozsiewanym przez lewicę bzdurom.",
    "wbrew temu‚ co bredzą eurokraci.", "wbrew rojeniom resortowych dzieci.",
    "wbrew temu‚ co myślą sobie młodzi wykształceni z wielkich miast.",
    "wbrew temu‚ co uroili sobie przeintelektualizowani wielkomiejscy intelektualiści.",
    "wbrew temu‚ co twierdzą lewicowi hipsterzy.",
    "wbrew temu‚ co uważa kawiorowa lewica.",
    "wbrew temu‚ co głosi kanapowa lewica.",
    "wbrew temu‚ co powtarzają PZPRowscy aparatczycy.",
    "wbrew temu‚ co mawia się na Placu Zbawiciela.",
    "wbrew temu co próbują nam wmówić koneserzy męskich odbytów.",
    "wbrew naiwnym przekonaniom lemingów.", "wbrew lewackim wymysłom.",
    "wbrew propagandzie cywilizacji śmierci.",
    "choć cyngle GazWybu wmawiają coś innego.",
    "choć oczywiście lewacy z TVNu mówią coś innego.",
    "choć WSI24 gada swoje.", "choć oczywiście media kłamią na ten temat.",
    "choć Biedroń i Grodzka oczywiście szerzą swoją propagandę.",
    "mimo kalumni mediów mętnego nurtu.",
    "choć dyrektywy z Brukseli mówią inaczej.",
    "choć wykształciuchy twierdzą swoje.",
    "chociaż łże-elity oczywiście głoszą swoje.",
    "wbrew temu co twierdzą oszałe ze wściekłości środowiska ateistyczne.",
    "wbrew temu co Urban twierdzi w swojej gadzinówce.",
    "wbrew temu co twierdzi skrajna lewica od Palikota.",
    "wbrew temu co twierdzą syjonistyczni agenci.",
    "wbrew głupotom mówionym przez bezstresowo wychowaną lewacką młodzież.",
    "wbrew temu co głosi TTDKN - tajne lewackie lobby sterowane z Brukseli.",
    "wbrew rojeniom komuszków.", "wbrew bredzeniom socjalistów.",
    "mimo propagandy agentów wpływu.",
    "mimo tego co twierdzą pachołki Moskwy.",
    "wbrew fantazjom waginosceptyków.",
    "wbrew opiniom skrajnie lewicowej blogerki Szproty.",
    "mimo rysunków stalinowskiej rysowniczki Kiciputek (czy to jest polskie nazwisko?).",
    "wbrew szyderstwom cyngla Michnika - Wojciecha Orlińskiego.",
    "wbrew temu co twierdzą zdrajcy Polski.",
    "wbrew temu co głoszą ludzie opętani nienawiścią do Kościoła.",
    "wbrew temu co uważają osoby kompletnie odklejone od rzeczywistości.",
    "wbrew temu co twierdzą byli esbecy.", "mimo wymysłów feminazistek.",
    "wbrew temu co twierdzi skrajnie lewicowa partia Razem.",
    "wbrew opiniom nowej ideolożki lewicy - Marceliny Zawiszy.",
    "wbrew postulatom Razem - nowej niebezpiecznej siły na lewicy.",
    "wbrew bredzeniom lewackich hipsterów z Partii Razem.",
    "wbrew temu co twierdzi Adrian Zandberg z Partii Razem.",
    "wbrew demagogii Macieja Koniecznego z Partii Razem.",
    "choć Partia Razem o niejasnych źródłach finansowania próbuje nam wmawiać inaczej.",
    "choć co innego mówi nam choćby Katarzyna Paprota z komunistycznej partii Razem.",
    "wbrew temu co głosi agresywne ekolobby.",
    "mimo rozpaczliwych pohukiwań marksistów-genderystów.",
    "czego by nie powiedziała cała ta lewacka hołota.",
    "wbrew oficjalnej ideologii masonów walczących z Bogiem i człowiekiem.",
    "i przyzna to nawet myślący ateista.",
    "wbrew planom lewactwa marzącego o urządzeniu nad Wisłą Korei Północnej.",
    "wbrew fanaberiom cywilizacji śmierci.",
    "mimo promowania tak zwanego równouprawnienia kobiet.",
    "wbrew ekoterrorystycznym fanaberiom.",
    "wbrew bzdurom głoszonym przez Zielonych.",
    "wbrew temu co twierdzi komuch Ikonowicz.",
    "wbrew zielonej propagandzie eko-komuchów."
]

FRAZY_PART_ЧЕТВЕРТЫЙ = [
    "Nie bójmy się tego głośno mówić.", "Czuję się jak u Barei!",
    "Po prostu mówię jak jest.", "Jest to zresztą temat zastępczy.",
    "Nie żyjemy w idealnym świecie.",
    "Musimy oczekiwać elementarnej odpowiedzialności.",
    "Uważam‚ że w tych sprawach powinno się kierować przede wszystkim zdrowym rozsądkiem.",
    "Nie wpadajmy ze skrajność w skrajność.", "Życie nie jest sprawiedliwe.",
    "Ale to typowo polskie podejście.",
    "Pamiętajmy o nauczaniu Jana Pawła II!",
    "Nie brnijmy w typowo polskie piekiełko.",
    "To poniżej wszelkiego poziomu.", "Ale o tym się nie pisze.",
    "Ale na pejsbuku o tym nie przeczytacie.",
    "Ale nie przeczytacie o tym w mediach głównego ścieku.",
    "Ja tylko zadaję pytania!", "Warto się zastanowić kto ma w tym interes?",
    "Ale POlityczna POprawność nie pozwala o tym wspominać.",
    "Naród wspaniały tylko ludzie kurwy.",
    "W cywilizowanym świecie to byłoby nie do pomyślenia!", "Jak za komuny!",
    "Ale wracają stalinowskie metody!",
    "Ale w tej atmosferze nie ma mowy o rzeczowej dyskusji.",
    "Taka jest natura ludzka.", "Wystarczy myśleć samodzielnie.",
    "Proszę mi to wytłumaczyć.", "Oczywiście za moje podatki.",
    "Ta afera jest grubymi nićmi szyta.", "Nie nazywajmy szamba perfumerią.",
    "Z faktami się nie dyskutuje.",
    "Ciekawe ile wam płacą na Czerskiej za te komentarze?",
    "Unia wam płaci za te brednie czy jesteście po prostu pożytecznymi idiotami?",
    "Przed wojną to by było nie do pomyślenia!",
    "To scenariusz realizowany od wielu lat przez syjonistów.",
    "Ale spisek związanych z Układem mediów nie pozwala mówić o tym głośno.",
    "Nie ma bowiem innej drogi wyjścia z matni niż porządne zajęcie się tą sprawą.",
    "Wierzę że także obecnie możliwe są odważne zdroworozsądkowe decyzje.",
    "I to nie jest tylko żenada ani obciach. To jest kompletna głupota.",
    "Pozostaje się tylko modlić.", "Ludzie w końcu muszą przejrzeć na oczy.",
    "To po prostu spisek!",
    "Nie zapominajmy o dziedzictwie Prezydenta Lecha Kaczyńskiego.",
    "Przykro mi ale taka jest prawda.", "To elementarna logika.",
    "Tu chodzi o polską rację stanu.", "Pomyślmy o dzieciach!",
    "Nie zapominajmy o naszym dziedzictwie narodowym.",
    "Nie można się z tym nie zgodzić.",
    "Chyba każdy myślący człowiek się z tym zgodzi?",
    "Nie wstydźmy się Ojczyzny!", "Himalaje absurdu!", "P.S. To prawda.",
    "Przestań wierzyć w to co mówi telewizja!",
    "Kto położy kres temu szaleństwu?", "Wolne żarty!", "A media milczą!",
    "Wystarczy zapytać polskich przedsiębiorców.", "A aferzyści się bogacą!",
    "I na takich nie ma POlicji!", "Nie o to walczyli żołnierze wyklęci!",
    "Mądremu dość.", "Polacy zaczynają się budzić i to dostrzegać.",
    "O tym nie wolno mówić?", "Polacy mają dość hołoty!",
    "Możemy być dumni z Polski!", "To kwestia nauki i polityki.",
    "Skąd się bierze tylu idiotów?", "A podobno komuna upadła w 1989!",
    "Ale oczywiście ludzie wolą iść po linii najmniejszego oporu.",
    "To poniżej wszelkiej krytyki.", "Z takimi ludźmi nie warto rozmawiać.",
    "Szkoda", "że w 1989 nikogo nie powieszono."
]


def główny():
    ''' Takie, takie, na szybkości. '''

    print(
        graj(FRAZY_PART_ONE) + ' ' + graj(FRAZY_PART_DWA) + ' ' + graj(
            FRAZY_PART_3) + ' ' + graj(FRAZY_PART_ЧЕТВЕРТЫЙ))

    return 0


def graj(frazy):
    ''' Losujemy od niechcenia. '''

    elemencik = loteriada(0, len(frazy)-1)

    return frazy[elemencik]


if __name__ == "__main__":
    exit(główny())
